# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pems.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npems.proto\"z\n\x04PeMS\x12\x12\n\nstation_id\x18\x01 \x01(\r\x12\x0c\n\x04time\x18\x02 \x01(\t\x12\x19\n\x05lanes\x18\x03 \x03(\x0b\x32\n.PeMS.Lane\x12\x10\n\x08observed\x18\x04 \x01(\x02\x1a#\n\x04Lane\x12\r\n\x05speed\x18\x01 \x01(\x02\x12\x0c\n\x04\x66low\x18\x02 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pems_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PEMS']._serialized_start=14
  _globals['_PEMS']._serialized_end=136
  _globals['_PEMS_LANE']._serialized_start=101
  _globals['_PEMS_LANE']._serialized_end=136
# @@protoc_insertion_point(module_scope)
