"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class PeMS(google.protobuf.message.Message):
    """import "bq_table.proto";
    import "bq_field.proto";
    package pems;

     option (gen_bq_schema.bigquery_opts).table_name = "pems";
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class Lane(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        SPEED_FIELD_NUMBER: builtins.int
        FLOW_FIELD_NUMBER: builtins.int
        speed: builtins.float
        flow: builtins.float
        def __init__(
            self,
            *,
            speed: builtins.float = ...,
            flow: builtins.float = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["flow", b"flow", "speed", b"speed"]) -> None: ...

    STATION_ID_FIELD_NUMBER: builtins.int
    TIME_FIELD_NUMBER: builtins.int
    LANES_FIELD_NUMBER: builtins.int
    OBSERVED_FIELD_NUMBER: builtins.int
    station_id: builtins.int
    time: builtins.str
    @property
    def lanes(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PeMS.Lane]: ...
    observed: builtins.float
    def __init__(
        self,
        *,
        station_id: builtins.int = ...,
        time: builtins.str = ...,
        lanes: collections.abc.Iterable[global___PeMS.Lane] | None = ...,
        observed: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["lanes", b"lanes", "observed", b"observed", "station_id", b"station_id", "time", b"time"]) -> None: ...

global___PeMS = PeMS
